allpowerdata<-read.csv("household_power_consumption.txt", sep=";")
useabledata<-subset(allpowerdata, Date =="1/2/2007" | Date == "2/2/2007")
x<-as.numeric(as.character(useabledata$Global_active_power))
dates<-paste(useabledata$Date, useabledata$Time)
finaldates<-strptime(dates, "%d/%m/%Y %H:%M:%S")
png("plot2.png", height=480, width=480)
plot(finaldates, x, type = "l", ylab = "Global Active Power (kilowatts)", xlab = "")
dev.off()
