allpowerdata<-read.csv("household_power_consumption.txt", sep=";")
useabledata<-subset(allpowerdata, Date =="1/2/2007" | Date == "2/2/2007")
x<-as.numeric(useabledata$Sub_metering_1)
y<-as.numeric(useabledata$Sub_metering_2)
z<-as.numeric(useabledata$Sub_metering_3)
len<-length(x)
png("plot3.png", height=480, width=480)
plot(x-2, type = "l", ylab = "Energy sub metering", xaxt="n", yaxt="n",ylim=c(0, max(x)), xlab="")
lines(y/10, type="l", col="red")
lines(z, type="l", col="blue")
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, col = c("black","red","blue"))
axis(side=1, at=seq(0,len, by=len/2), labels=c("Thu", "Fri", "Sat"))
axis(side=2, at=seq(0,max(x), by=10))
dev.off()